name: Deploying to github-pages

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test
    - run: npm run build
    - run: npm run deploy
